### ISSUE TITLE
About the mod and TODO list

### ISSUE THREAD

**Issue by Megaf** [Megaf/halloween_mod#1]
# Halloween Mod
## About:
Sol, Halloween Mod is a decoration mod, for Halloween.
It will be spooky, shadowy, scary. Here is a list of items that we would like to add.
I know there are already mods that have some of the items, we can borrow these items and add to this mod too.
## TODO
- [ ] Skull A
- [ ] Skull B
- [ ] Pumpkin A
- [ ] Pumpkin B
- [ ] Spider
- [ ] Spider webs
- [ ] Dark soil. Maybe with blood stains.
- [ ] Wood planks with dark textures and blood stains
- [ ] Scare crows and crows
- [ ] Blood, node type like a curtain or a paint that we can add to existing walls.

More ideas?

**Comment by SmallJoker** [comment]
- [ ] Ghost mobs (when a mod API was found)
- [ ] Nodes that spawn blood particles underground
- [ ] Halloween-Sounds

**Comment by Megaf** [comment]
We definitely need Halloween sounds yes. Blood particle spawner would be cool yes.
Not sure if mobs would be a good idea, only if they are extremely simple and light.
